version: "3.0"

services:
  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  yopass:
    image: yopass-onboarding:1.21.0
    restart: always
    ports:
      - "127.0.0.1:80:80"
    command: "--memcached=memcached:11211 --port 80"
